language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_EXTRA_ARGS

script:
  - composer lint
  - composer cs
