language: php

sudo: false

env:
  - NETTE=default
  - NETTE=~3.0.0
  - NETTE=~3.0.0 PREFER_LOWEST=true

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

before_install:
  - composer self-update
  - php .travis.composer.php

install:
  - composer install --no-interaction --prefer-source --ignore-platform-reqs
  - if  [ $PREFER_LOWEST = 'true' ]; then composer update --prefer-lowest --prefer-stable --ignore-platform-reqs; fi

script:
  - vendor/bin/parallel-lint -e php,phpt src
  - vendor/bin/phpcs -sp --standard=vendor/nella/coding-standard/Nella/ruleset.xml src
